cloud-function:
  - changed-files:
      - any-glob-to-any-file: "cloud-function/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/poetry.lock"
          - "**/yarn.lock"

deployer:
  - changed-files:
      - any-glob-to-any-file: "deployer/**/*"

filecheck:
  - changed-files:
      - any-glob-to-any-file: "filecheck/**/*"

github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**/*"

python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"
