pre-commit:
  parallel: true
  jobs:
    - name: prettier
      run: npx prettier --write --cache --ignore-unknown {staged_files}
      stage_fixed: true

    - name: eslint
      run: npx eslint --fix --cache {staged_files}
      glob:
        - "*.js"
        - "*.jsx"
        - "*.ts"
        - "*.tsx"
      stage_fixed: true

    - name: eslint (global)
      run: npx eslint --fix --cache .
      glob: .eslintrc.cjs
      stage_fixed: true

pre-push:
  piped: true
  jobs:
    - run: npm install

    - name: lint
      group:
        parrallel: true
        jobs:
          - name: eslint
            run: npx eslint --cache
          - name: tsc
            run: npm run check:tsc

post-merge:
  only:
    - ref: main
  commands:
    npm-install:
      run: npm install --ignore-scripts

output:
  - summary
  - failure
