name: Sync play from Fred

on:
  workflow_dispatch:

  schedule:
    - cron: "30 4 * * *"

permissions: {} # No GITHUB_TOKEN permissions, because we use MDN_BOT_PAT instead.

jobs:
  sync:
    if: github.repository == 'mdn/dex'
    name: Sync play/index.js from Fred
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dex)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Fetch play/index.js from Fred
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/mdn/fred/main/vendor/yari/libs/play/index.js \
            -o cloud-function/src/internal/play/index.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.MDN_BOT_PAT }}
          commit-message: "chore(play): sync index.js from Fred"
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          signoff: false
          branch: sync-play
          delete-branch: true
          add-paths: cloud-function/src/internal/play/index.js
          title: "chore(play): sync index.js from Fred"
          body: |
            Sync `cloud-function/src/internal/play/index.js` from [`vendor/yari/libs/play/index.js`](https://github.com/mdn/fred/blob/main/vendor/yari/libs/play/index.js) in `mdn/fred`.

            (This PR was generated by [this run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) of the [`${{ github.workflow }}`](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/sync-play.yml) workflow.)
          draft: false
